// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Rel(arg1:string,arg2:string):Promise<string>;

export function SelectGoProject():Promise<Record<string, Array<string>>>;

export function Step():Promise<main.StepResult>;

export function Trace(arg1:Array<string>):Promise<string>;
