// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Rel(arg1, arg2) {
  return window['go']['main']['App']['Rel'](arg1, arg2);
}

export function SelectGoProject() {
  return window['go']['main']['App']['SelectGoProject']();
}

export function Step() {
  return window['go']['main']['App']['Step']();
}

export function Trace(arg1) {
  return window['go']['main']['App']['Trace'](arg1);
}
